host: localhost
port: 8000
maxUploadSizeMB: 1024

# this should point to a directory that will be used
# to contain the database and image/video files
storageDir: /path/to/imgbox

# this should point to a directory that contains the
# content of static/... in this repository
staticDir: /path/to/static
